spring:
    datasource:
        url: jdbc:h2:mem:default;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
        driverClassName: org.h2.Driver
        username: sa
        password: ""
jpa:
    default:
        packages-to-scan:
            - 'example' # <1>
        properties:
            hibernate:
                hbm2ddl:
                    auto: update
                show_sql: true
                dialect: H2
                bytecode:
                    provider: none